### ISSUE TITLE
Version 1.2.0 Bugs

### ISSUE THREAD

**Issue by brickworm2012** [StarQuestMinecraft/LimitlessBugs#18] opened 2016-12-31 16:44 UTC
Probably will update as I find more. 
On Windows 10, x32
-Exit to main menu button doesn't work some of the time EDIT: Fierce's bug report
-EDITED
-water fills any space immediately as a full block
-vehicles despawn, either immediately or quickly after p is pressed, or drop and become blocks again
-long grass don't render. EDITED

**Comment by dphfox** [comment] 2017-01-03 18:58
Old worlds are not supported anymore, since the terrain generation was
temporary. You'll need to create a new world. Also instant water occupancy
is intentional; since it implies the block was already saturated with water
(similar to reality; if you dig a deep enough hole water would seep in,
this is known as the water table)

*Elttob*

**Comment by martinjonsson01** [comment] 2017-01-04 02:16
The both left click and right click breaks blocks part is probably @GingerWalnut 's area.

**Comment by GingerWalnut** [comment] 2017-01-05 14:35
The left click/right click is not a bug, its just part of the new hotbar system. I dont think we told anyone how it works though, so it isnt something you missed.

**Comment by GingerWalnut** [comment] 2017-04-13 14:36
All of these bugs should be fixed in the next release or are not bugs and are intended behaviors.

**Closed as completed by GingerWalnut** 2017-04-13 14:36 UTC
